# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mineinfo.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MinePage(object):
    def setupUi(self, MinePage):
        MinePage.setObjectName(_fromUtf8("MinePage"))
        MinePage.resize(400, 300)
        self.verticalLayout_5 = QtGui.QVBoxLayout(MinePage)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_7 = QtGui.QLabel(MinePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(378, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.line_2 = QtGui.QFrame(MinePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.mineTypeLabel = QtGui.QLabel(MinePage)
        self.mineTypeLabel.setObjectName(_fromUtf8("mineTypeLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.mineTypeLabel)
        self.mineTypeCombo = QtGui.QComboBox(MinePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mineTypeCombo.sizePolicy().hasHeightForWidth())
        self.mineTypeCombo.setSizePolicy(sizePolicy)
        self.mineTypeCombo.setObjectName(_fromUtf8("mineTypeCombo"))
        self.mineTypeCombo.addItem(_fromUtf8(""))
        self.mineTypeCombo.addItem(_fromUtf8(""))
        self.mineTypeCombo.addItem(_fromUtf8(""))
        self.mineTypeCombo.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.mineTypeCombo)
        self.factorOfSafetyLabel = QtGui.QLabel(MinePage)
        self.factorOfSafetyLabel.setObjectName(_fromUtf8("factorOfSafetyLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.factorOfSafetyLabel)
        self.fosDoubleSpin = QtGui.QDoubleSpinBox(MinePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fosDoubleSpin.sizePolicy().hasHeightForWidth())
        self.fosDoubleSpin.setSizePolicy(sizePolicy)
        self.fosDoubleSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fosDoubleSpin.setObjectName(_fromUtf8("fosDoubleSpin"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.fosDoubleSpin)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_8 = QtGui.QLabel(MinePage)
        self.label_8.setMinimumSize(QtCore.QSize(378, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.line_3 = QtGui.QFrame(MinePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_2.addWidget(self.line_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(MinePage)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.sampleHeightSpin = QtGui.QDoubleSpinBox(MinePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleHeightSpin.sizePolicy().hasHeightForWidth())
        self.sampleHeightSpin.setSizePolicy(sizePolicy)
        self.sampleHeightSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sampleHeightSpin.setObjectName(_fromUtf8("sampleHeightSpin"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.sampleHeightSpin)
        self.label_2 = QtGui.QLabel(MinePage)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.doubleSpinBox_7 = QtGui.QDoubleSpinBox(MinePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_7.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_7.setSizePolicy(sizePolicy)
        self.doubleSpinBox_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_7.setMaximum(90.0)
        self.doubleSpinBox_7.setObjectName(_fromUtf8("doubleSpinBox_7"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_7)
        self.label_3 = QtGui.QLabel(MinePage)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.sampleHeightSpin_2 = QtGui.QDoubleSpinBox(MinePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleHeightSpin_2.sizePolicy().hasHeightForWidth())
        self.sampleHeightSpin_2.setSizePolicy(sizePolicy)
        self.sampleHeightSpin_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sampleHeightSpin_2.setObjectName(_fromUtf8("sampleHeightSpin_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.sampleHeightSpin_2)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 79, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.mineTypeLabel.setBuddy(self.mineTypeCombo)
        self.factorOfSafetyLabel.setBuddy(self.fosDoubleSpin)

        self.retranslateUi(MinePage)
        QtCore.QMetaObject.connectSlotsByName(MinePage)

    def retranslateUi(self, MinePage):
        MinePage.setWindowTitle(_translate("MinePage", "General and Geological Information", None))
        MinePage.setTitle(_translate("MinePage", "General and Geological Information", None))
        self.label_7.setText(_translate("MinePage", "General Information", None))
        self.mineTypeLabel.setText(_translate("MinePage", "&Mine Type:", None))
        self.mineTypeCombo.setItemText(0, _translate("MinePage", "Coal", None))
        self.mineTypeCombo.setItemText(1, _translate("MinePage", "Hard Rock", None))
        self.mineTypeCombo.setItemText(2, _translate("MinePage", "Oil Shale", None))
        self.mineTypeCombo.setItemText(3, _translate("MinePage", "Others", None))
        self.factorOfSafetyLabel.setText(_translate("MinePage", "&Factor of Safety:", None))
        self.label_8.setText(_translate("MinePage", "Geological Parameters", None))
        self.label.setText(_translate("MinePage", "Overburden Height:", None))
        self.sampleHeightSpin.setSuffix(_translate("MinePage", " m", None))
        self.label_2.setText(_translate("MinePage", "Seam Dip:", None))
        self.doubleSpinBox_7.setSuffix(_translate("MinePage", " °", None))
        self.label_3.setText(_translate("MinePage", "Seam Height:", None))
        self.sampleHeightSpin_2.setSuffix(_translate("MinePage", " m", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MinePage = QtGui.QWizardPage()
    ui = Ui_MinePage()
    ui.setupUi(MinePage)
    MinePage.show()
    sys.exit(app.exec_())

