# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wizard.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName(_fromUtf8("Wizard"))
        Wizard.resize(570, 401)
        Wizard.setWizardStyle(QtGui.QWizard.ModernStyle)
        self.introPage = QtGui.QWizardPage()
        self.introPage.setObjectName(_fromUtf8("introPage"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.introPage)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.textEdit = QtGui.QTextEdit(self.introPage)
        self.textEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_17.addWidget(self.textEdit)
        Wizard.addPage(self.introPage)
        self.projectDetailsPage = QtGui.QWizardPage()
        self.projectDetailsPage.setObjectName(_fromUtf8("projectDetailsPage"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.projectDetailsPage)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.scrollArea = QtGui.QScrollArea(self.projectDetailsPage)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 552, 340))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.line = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.projectNameLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.projectNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.projectNameLabel.setObjectName(_fromUtf8("projectNameLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.projectNameLabel)
        self.projectNameLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.projectNameLineEdit.setObjectName(_fromUtf8("projectNameLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.projectNameLineEdit)
        self.locationLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.locationLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.locationLabel.setObjectName(_fromUtf8("locationLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.locationLabel)
        self.locationComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.locationComboBox.setEditable(True)
        self.locationComboBox.setObjectName(_fromUtf8("locationComboBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.locationComboBox)
        self.oreTypeLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.oreTypeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.oreTypeLabel.setObjectName(_fromUtf8("oreTypeLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.oreTypeLabel)
        self.oreTypeComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.oreTypeComboBox.setEditable(True)
        self.oreTypeComboBox.setObjectName(_fromUtf8("oreTypeComboBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.oreTypeComboBox)
        self.horizontalLayout_2.addLayout(self.formLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.stateRadio = QtGui.QRadioButton(self.scrollAreaWidgetContents)
        self.stateRadio.setCheckable(True)
        self.stateRadio.setChecked(True)
        self.stateRadio.setObjectName(_fromUtf8("stateRadio"))
        self.horizontalLayout_3.addWidget(self.stateRadio)
        self.redesignRadio = QtGui.QRadioButton(self.scrollAreaWidgetContents)
        self.redesignRadio.setObjectName(_fromUtf8("redesignRadio"))
        self.horizontalLayout_3.addWidget(self.redesignRadio)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_12.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_2.addWidget(self.line_2)
        self.verticalLayout_12.addLayout(self.verticalLayout_2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.minExtractionLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.minExtractionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minExtractionLabel.setObjectName(_fromUtf8("minExtractionLabel"))
        self.gridLayout_2.addWidget(self.minExtractionLabel, 0, 0, 1, 1)
        self.minExtractionSpinBox = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.minExtractionSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minExtractionSpinBox.setPrefix(_fromUtf8(""))
        self.minExtractionSpinBox.setDecimals(1)
        self.minExtractionSpinBox.setMaximum(90.0)
        self.minExtractionSpinBox.setProperty("value", 50.0)
        self.minExtractionSpinBox.setObjectName(_fromUtf8("minExtractionSpinBox"))
        self.gridLayout_2.addWidget(self.minExtractionSpinBox, 0, 1, 1, 1)
        self.roomWidthLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.roomWidthLabel.setObjectName(_fromUtf8("roomWidthLabel"))
        self.gridLayout_2.addWidget(self.roomWidthLabel, 1, 0, 1, 1)
        self.roomWidthSpinBox = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.roomWidthSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roomWidthSpinBox.setMaximum(20.0)
        self.roomWidthSpinBox.setProperty("value", 6.0)
        self.roomWidthSpinBox.setObjectName(_fromUtf8("roomWidthSpinBox"))
        self.gridLayout_2.addWidget(self.roomWidthSpinBox, 1, 1, 1, 1)
        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_11.setContentsMargins(0, -1, -1, 1)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_4 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_11.addWidget(self.label_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.drillBlastRadio = QtGui.QRadioButton(self.frame)
        self.drillBlastRadio.setChecked(True)
        self.drillBlastRadio.setObjectName(_fromUtf8("drillBlastRadio"))
        self.horizontalLayout.addWidget(self.drillBlastRadio)
        self.continuousMinerRadio = QtGui.QRadioButton(self.frame)
        self.continuousMinerRadio.setObjectName(_fromUtf8("continuousMinerRadio"))
        self.horizontalLayout.addWidget(self.continuousMinerRadio)
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        self.gridLayout_2.addWidget(self.frame, 2, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 3, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 50, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        Wizard.addPage(self.projectDetailsPage)
        self.pillarStrengthPage = QtGui.QWizardPage()
        self.pillarStrengthPage.setObjectName(_fromUtf8("pillarStrengthPage"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.pillarStrengthPage)
        self.verticalLayout_14.setSpacing(16)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_6 = QtGui.QLabel(self.pillarStrengthPage)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.pillarFormulaComboBox = QtGui.QComboBox(self.pillarStrengthPage)
        self.pillarFormulaComboBox.setObjectName(_fromUtf8("pillarFormulaComboBox"))
        self.gridLayout_4.addWidget(self.pillarFormulaComboBox, 0, 1, 2, 1)
        self.label_12 = QtGui.QLabel(self.pillarStrengthPage)
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 2, 0, 1, 2)
        self.label_11 = QtGui.QLabel(self.pillarStrengthPage)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 3, 0, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 2, 4, 1)
        self.verticalLayout_14.addLayout(self.gridLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_13.setSpacing(1)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_5 = QtGui.QLabel(self.pillarStrengthPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_13.addWidget(self.label_5)
        self.line_5 = QtGui.QFrame(self.pillarStrengthPage)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_13.addWidget(self.line_5)
        self.verticalLayout_5.addLayout(self.verticalLayout_13)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.constantKLabel = QtGui.QLabel(self.pillarStrengthPage)
        self.constantKLabel.setObjectName(_fromUtf8("constantKLabel"))
        self.gridLayout_3.addWidget(self.constantKLabel, 0, 0, 1, 1)
        self.constantKDoubleSpinBox = QtGui.QDoubleSpinBox(self.pillarStrengthPage)
        self.constantKDoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.constantKDoubleSpinBox.setDecimals(3)
        self.constantKDoubleSpinBox.setMaximum(500.0)
        self.constantKDoubleSpinBox.setProperty("value", 15.0)
        self.constantKDoubleSpinBox.setObjectName(_fromUtf8("constantKDoubleSpinBox"))
        self.gridLayout_3.addWidget(self.constantKDoubleSpinBox, 0, 1, 1, 1)
        self.constantALabel = QtGui.QLabel(self.pillarStrengthPage)
        self.constantALabel.setObjectName(_fromUtf8("constantALabel"))
        self.gridLayout_3.addWidget(self.constantALabel, 0, 2, 1, 1)
        self.constantADoubleSpinBox = QtGui.QDoubleSpinBox(self.pillarStrengthPage)
        self.constantADoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.constantADoubleSpinBox.setDecimals(3)
        self.constantADoubleSpinBox.setMinimum(-1.0)
        self.constantADoubleSpinBox.setMaximum(1.0)
        self.constantADoubleSpinBox.setProperty("value", -0.6)
        self.constantADoubleSpinBox.setObjectName(_fromUtf8("constantADoubleSpinBox"))
        self.gridLayout_3.addWidget(self.constantADoubleSpinBox, 0, 3, 1, 1)
        self.bLabel = QtGui.QLabel(self.pillarStrengthPage)
        self.bLabel.setObjectName(_fromUtf8("bLabel"))
        self.gridLayout_3.addWidget(self.bLabel, 0, 4, 1, 1)
        self.constantBDoubleSpinBox = QtGui.QDoubleSpinBox(self.pillarStrengthPage)
        self.constantBDoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.constantBDoubleSpinBox.setDecimals(3)
        self.constantBDoubleSpinBox.setMinimum(-1.0)
        self.constantBDoubleSpinBox.setMaximum(1.0)
        self.constantBDoubleSpinBox.setProperty("value", 0.4)
        self.constantBDoubleSpinBox.setObjectName(_fromUtf8("constantBDoubleSpinBox"))
        self.gridLayout_3.addWidget(self.constantBDoubleSpinBox, 0, 5, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 6, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.verticalLayout_14.addLayout(self.verticalLayout_5)
        spacerItem6 = QtGui.QSpacerItem(20, 139, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem6)
        Wizard.addPage(self.pillarStrengthPage)
        self.geoPage = QtGui.QWizardPage()
        self.geoPage.setObjectName(_fromUtf8("geoPage"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.geoPage)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.scrollArea_2 = QtGui.QScrollArea(self.geoPage)
        self.scrollArea_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 552, 340))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(378, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_10.addWidget(self.label_8)
        self.line_4 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_10.addWidget(self.line_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_10)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cohesionLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.cohesionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cohesionLabel.setObjectName(_fromUtf8("cohesionLabel"))
        self.gridLayout.addWidget(self.cohesionLabel, 2, 0, 1, 1)
        self.cohesionDoubleSpinBox = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.cohesionDoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cohesionDoubleSpinBox.setProperty("value", 0.2)
        self.cohesionDoubleSpinBox.setObjectName(_fromUtf8("cohesionDoubleSpinBox"))
        self.gridLayout.addWidget(self.cohesionDoubleSpinBox, 2, 1, 2, 1)
        self.sampleHeightLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.sampleHeightLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sampleHeightLabel.setObjectName(_fromUtf8("sampleHeightLabel"))
        self.gridLayout.addWidget(self.sampleHeightLabel, 2, 2, 1, 1)
        self.sampleHeightDoubleSpinBox = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.sampleHeightDoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sampleHeightDoubleSpinBox.setProperty("value", 1.0)
        self.sampleHeightDoubleSpinBox.setObjectName(_fromUtf8("sampleHeightDoubleSpinBox"))
        self.gridLayout.addWidget(self.sampleHeightDoubleSpinBox, 2, 3, 2, 2)
        self.uniaxialCompressiveStrengthLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.uniaxialCompressiveStrengthLabel.setObjectName(_fromUtf8("uniaxialCompressiveStrengthLabel"))
        self.gridLayout.addWidget(self.uniaxialCompressiveStrengthLabel, 1, 0, 1, 2)
        self.uniaxStrengthDoubleSpinBox = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.uniaxStrengthDoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uniaxStrengthDoubleSpinBox.setMaximum(1000.0)
        self.uniaxStrengthDoubleSpinBox.setProperty("value", 38.47)
        self.uniaxStrengthDoubleSpinBox.setObjectName(_fromUtf8("uniaxStrengthDoubleSpinBox"))
        self.gridLayout.addWidget(self.uniaxStrengthDoubleSpinBox, 1, 2, 1, 1)
        self.rmrLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.rmrLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rmrLabel.setObjectName(_fromUtf8("rmrLabel"))
        self.gridLayout.addWidget(self.rmrLabel, 1, 3, 1, 1)
        self.rmrSpinBox = QtGui.QSpinBox(self.scrollAreaWidgetContents_2)
        self.rmrSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rmrSpinBox.setMaximum(100)
        self.rmrSpinBox.setProperty("value", 44)
        self.rmrSpinBox.setObjectName(_fromUtf8("rmrSpinBox"))
        self.gridLayout.addWidget(self.rmrSpinBox, 1, 4, 1, 1)
        self.sampleDiameterLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.sampleDiameterLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sampleDiameterLabel.setObjectName(_fromUtf8("sampleDiameterLabel"))
        self.gridLayout.addWidget(self.sampleDiameterLabel, 4, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(73, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 5, 5, 1)
        self.sampleDiameterDoubleSpinBox = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.sampleDiameterDoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sampleDiameterDoubleSpinBox.setProperty("value", 1.0)
        self.sampleDiameterDoubleSpinBox.setObjectName(_fromUtf8("sampleDiameterDoubleSpinBox"))
        self.gridLayout.addWidget(self.sampleDiameterDoubleSpinBox, 4, 3, 1, 2)
        self.frictionAngleDoubleSpinBox = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.frictionAngleDoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.frictionAngleDoubleSpinBox.setMaximum(90.0)
        self.frictionAngleDoubleSpinBox.setProperty("value", 19.0)
        self.frictionAngleDoubleSpinBox.setObjectName(_fromUtf8("frictionAngleDoubleSpinBox"))
        self.gridLayout.addWidget(self.frictionAngleDoubleSpinBox, 4, 1, 1, 1)
        self.frictionAngleLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.frictionAngleLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.frictionAngleLabel.setObjectName(_fromUtf8("frictionAngleLabel"))
        self.gridLayout.addWidget(self.frictionAngleLabel, 4, 0, 1, 1)
        self.cylindricalSampleRadio = QtGui.QRadioButton(self.scrollAreaWidgetContents_2)
        self.cylindricalSampleRadio.setObjectName(_fromUtf8("cylindricalSampleRadio"))
        self.gridLayout.addWidget(self.cylindricalSampleRadio, 0, 0, 1, 1)
        self.cuboidSampleRadio = QtGui.QRadioButton(self.scrollAreaWidgetContents_2)
        self.cuboidSampleRadio.setObjectName(_fromUtf8("cuboidSampleRadio"))
        self.gridLayout.addWidget(self.cuboidSampleRadio, 0, 1, 1, 2)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.verticalLayout_16.addLayout(self.verticalLayout_6)
        spacerItem8 = QtGui.QSpacerItem(20, 43, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem8)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_15.setSpacing(9)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(378, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_9.addWidget(self.label_7)
        self.line_3 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_9.addWidget(self.line_3)
        self.verticalLayout_15.addLayout(self.verticalLayout_9)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.oreDepthDoubleSpin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oreDepthDoubleSpin.sizePolicy().hasHeightForWidth())
        self.oreDepthDoubleSpin.setSizePolicy(sizePolicy)
        self.oreDepthDoubleSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.oreDepthDoubleSpin.setMaximum(1000.0)
        self.oreDepthDoubleSpin.setProperty("value", 150.0)
        self.oreDepthDoubleSpin.setObjectName(_fromUtf8("oreDepthDoubleSpin"))
        self.gridLayout_5.addWidget(self.oreDepthDoubleSpin, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 0, 2, 1, 1)
        self.seamDipDoubleSpin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seamDipDoubleSpin.sizePolicy().hasHeightForWidth())
        self.seamDipDoubleSpin.setSizePolicy(sizePolicy)
        self.seamDipDoubleSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.seamDipDoubleSpin.setMaximum(90.0)
        self.seamDipDoubleSpin.setProperty("value", 15.0)
        self.seamDipDoubleSpin.setObjectName(_fromUtf8("seamDipDoubleSpin"))
        self.gridLayout_5.addWidget(self.seamDipDoubleSpin, 0, 3, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem9, 0, 4, 2, 1)
        self.overburdenDensityLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.overburdenDensityLabel.setObjectName(_fromUtf8("overburdenDensityLabel"))
        self.gridLayout_5.addWidget(self.overburdenDensityLabel, 1, 0, 1, 1)
        self.overburdenDensityDoubleSpinBox = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overburdenDensityDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.overburdenDensityDoubleSpinBox.setSizePolicy(sizePolicy)
        self.overburdenDensityDoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.overburdenDensityDoubleSpinBox.setSuffix(_fromUtf8(""))
        self.overburdenDensityDoubleSpinBox.setMaximum(1000.0)
        self.overburdenDensityDoubleSpinBox.setProperty("value", 20.0)
        self.overburdenDensityDoubleSpinBox.setObjectName(_fromUtf8("overburdenDensityDoubleSpinBox"))
        self.gridLayout_5.addWidget(self.overburdenDensityDoubleSpinBox, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 1, 2, 1, 1)
        self.seamHeightDoubleSpin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seamHeightDoubleSpin.sizePolicy().hasHeightForWidth())
        self.seamHeightDoubleSpin.setSizePolicy(sizePolicy)
        self.seamHeightDoubleSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.seamHeightDoubleSpin.setProperty("value", 4.0)
        self.seamHeightDoubleSpin.setObjectName(_fromUtf8("seamHeightDoubleSpin"))
        self.gridLayout_5.addWidget(self.seamHeightDoubleSpin, 1, 3, 1, 1)
        self.verticalLayout_15.addLayout(self.gridLayout_5)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        spacerItem10 = QtGui.QSpacerItem(20, 24, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem10)
        self.cylindricalSampleRadio.raise_()
        self.cuboidSampleRadio.raise_()
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.addWidget(self.scrollArea_2)
        Wizard.addPage(self.geoPage)
        self.projectNameLabel.setBuddy(self.projectNameLineEdit)
        self.locationLabel.setBuddy(self.locationComboBox)
        self.oreTypeLabel.setBuddy(self.oreTypeComboBox)
        self.minExtractionLabel.setBuddy(self.minExtractionSpinBox)
        self.roomWidthLabel.setBuddy(self.roomWidthSpinBox)
        self.label_6.setBuddy(self.pillarFormulaComboBox)
        self.constantKLabel.setBuddy(self.constantKDoubleSpinBox)
        self.constantALabel.setBuddy(self.constantADoubleSpinBox)
        self.bLabel.setBuddy(self.constantBDoubleSpinBox)
        self.cohesionLabel.setBuddy(self.cohesionDoubleSpinBox)
        self.sampleHeightLabel.setBuddy(self.sampleHeightDoubleSpinBox)
        self.uniaxialCompressiveStrengthLabel.setBuddy(self.uniaxStrengthDoubleSpinBox)
        self.rmrLabel.setBuddy(self.rmrSpinBox)
        self.sampleDiameterLabel.setBuddy(self.sampleDiameterDoubleSpinBox)
        self.frictionAngleLabel.setBuddy(self.frictionAngleDoubleSpinBox)
        self.label_3.setBuddy(self.oreDepthDoubleSpin)
        self.label_9.setBuddy(self.seamDipDoubleSpin)
        self.overburdenDensityLabel.setBuddy(self.overburdenDensityDoubleSpinBox)
        self.label_10.setBuddy(self.seamHeightDoubleSpin)

        self.retranslateUi(Wizard)
        self.locationComboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        Wizard.setWindowTitle(_translate("Wizard", "Wizard", None))
        self.textEdit.setHtml(_translate("Wizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">Read the following carefully</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">This wizard will guide you through creating a new room and pillar (RAP) project. Defaults have been supplied for each of the various fields required. Please change these defaults to values that actually appy to your project.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">On the project details page, if you select </span><span style=\" font-size:10pt; font-style:italic;\">initial design</span><span style=\" font-size:10pt;\"> as the design type, the other data you entered will be used to evaluate the best method for design your RAP project. Choosing </span><span style=\" font-size:10pt; font-style:italic;\">redesign</span><span style=\" font-size:10pt;\"> allows you more control over the methods used to design your RAP project. It is also expected that you will have more geotechnical data in such a situation and as such so may need to supply some parameters.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">All thanks from </span><span style=\" font-size:10pt; font-style:italic;\">Charis</span><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">OS</span><span style=\" font-size:10pt;\"> and good luck.</span></p></body></html>", None))
        self.label.setText(_translate("Wizard", "General Information", None))
        self.projectNameLabel.setText(_translate("Wizard", "&Project Name:", None))
        self.locationLabel.setText(_translate("Wizard", "&Location:", None))
        self.oreTypeLabel.setText(_translate("Wizard", "&Ore Type:", None))
        self.stateRadio.setText(_translate("Wizard", "&Initial Design", None))
        self.redesignRadio.setText(_translate("Wizard", "&Redesign", None))
        self.label_2.setText(_translate("Wizard", "Other Information", None))
        self.minExtractionLabel.setText(_translate("Wizard", "&Minimum Extraction:", None))
        self.minExtractionSpinBox.setSuffix(_translate("Wizard", " %", None))
        self.roomWidthLabel.setText(_translate("Wizard", "Initial Room &Width:", None))
        self.roomWidthSpinBox.setSuffix(_translate("Wizard", " m", None))
        self.label_4.setText(_translate("Wizard", "Method of Fragmentation", None))
        self.drillBlastRadio.setToolTip(_translate("Wizard", "Method by which the ore will be fragmented", None))
        self.drillBlastRadio.setStatusTip(_translate("Wizard", "Method by which the ore will be fragmented", None))
        self.drillBlastRadio.setText(_translate("Wizard", "&Drill and Blast", None))
        self.continuousMinerRadio.setToolTip(_translate("Wizard", "Method by which the ore will be fragmented", None))
        self.continuousMinerRadio.setStatusTip(_translate("Wizard", "Method by which the ore will be fragmented", None))
        self.continuousMinerRadio.setText(_translate("Wizard", "&Continuous Miner", None))
        self.label_6.setText(_translate("Wizard", "&Pillar Strength Formula:", None))
        self.label_12.setText(_translate("Wizard", "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Type 1 S</span><span style=\" font-size:14pt; vertical-align:sub;\">P</span><span style=\" font-size:14pt;\"> = <span style=\" font-size:14pt; color:#ff0000;\">k</span>H</span><span style=\" font-size:14pt; color:#ff0000; vertical-align:super;\">A</span><span style=\" font-size:14pt;\">W</span><span style=\" font-size:14pt; color:#ff0000; vertical-align:super;\">B                  </span></p>\n"
"", None))
        self.label_11.setText(_translate("Wizard", "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Type 2  S</span><span style=\" font-size:14pt; vertical-align:sub;\">P</span><span style=\" font-size:14pt;\"> = </span><span style=\" font-size:14pt; color:#ff0000;\">k</span><span style=\" font-size:14pt;\">(</span><span style=\" font-size:14pt; color:#ff0000;\">A</span><span style=\" font-size:14pt;\"> + </span><span style=\" font-size:14pt; color:#ff0000;\">B</span><span style=\" font-size:14pt;\">(H/W))</span></p>", None))
        self.label_5.setText(_translate("Wizard", "Formula Constants", None))
        self.constantKLabel.setText(_translate("Wizard", "Const &k:", None))
        self.constantALabel.setText(_translate("Wizard", "Const &A:", None))
        self.bLabel.setText(_translate("Wizard", "Const &B:", None))
        self.label_8.setText(_translate("Wizard", "Geotechnical Information", None))
        self.cohesionLabel.setText(_translate("Wizard", "&Cohesion:", None))
        self.sampleHeightLabel.setText(_translate("Wizard", "Sample &Height:", None))
        self.sampleHeightDoubleSpinBox.setSuffix(_translate("Wizard", " m", None))
        self.uniaxialCompressiveStrengthLabel.setText(_translate("Wizard", "&Uniaxial Compressive Strength:", None))
        self.uniaxStrengthDoubleSpinBox.setSuffix(_translate("Wizard", " MPa", None))
        self.rmrLabel.setText(_translate("Wizard", "&RMR:", None))
        self.sampleDiameterLabel.setText(_translate("Wizard", "Sample &Diameter:", None))
        self.sampleDiameterDoubleSpinBox.setSuffix(_translate("Wizard", " m", None))
        self.frictionAngleDoubleSpinBox.setSuffix(_translate("Wizard", " °", None))
        self.frictionAngleLabel.setText(_translate("Wizard", "&Friction Angle:", None))
        self.cylindricalSampleRadio.setText(_translate("Wizard", "&Cy&lindrical Sample", None))
        self.cuboidSampleRadio.setText(_translate("Wizard", "Cu&be/Cuboid Sample", None))
        self.label_7.setText(_translate("Wizard", "Geological Information", None))
        self.label_3.setText(_translate("Wizard", "&Depth of Mine:", None))
        self.oreDepthDoubleSpin.setSuffix(_translate("Wizard", " m", None))
        self.label_9.setText(_translate("Wizard", "Sea&m Dip:", None))
        self.seamDipDoubleSpin.setSuffix(_translate("Wizard", " °", None))
        self.overburdenDensityLabel.setText(_translate("Wizard", "<html><head/><body><p>&amp;Overburden SG (kN/m<span style=\" vertical-align:super;\">3</span>):</p></body></html>", None))
        self.label_10.setText(_translate("Wizard", "Seam Hei&ght:", None))
        self.seamHeightDoubleSpin.setSuffix(_translate("Wizard", " m", None))

