# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wizard.ui'
#
# Created: Sat Apr 22 08:38:35 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName("Wizard")
        Wizard.resize(570, 401)
        Wizard.setWizardStyle(QtGui.QWizard.ModernStyle)
        self.introPage = QtGui.QWizardPage()
        self.introPage.setObjectName("introPage")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.introPage)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.textEdit = QtGui.QTextEdit(self.introPage)
        self.textEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit.setLineWidth(0)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_17.addWidget(self.textEdit)
        Wizard.addPage(self.introPage)
        self.projectDetailsPage = QtGui.QWizardPage()
        self.projectDetailsPage.setObjectName("projectDetailsPage")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.projectDetailsPage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea = QtGui.QScrollArea(self.projectDetailsPage)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 552, 336))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setSpacing(13)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.oreTypeLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.oreTypeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.oreTypeLabel.setObjectName("oreTypeLabel")
        self.gridLayout_4.addWidget(self.oreTypeLabel, 3, 0, 1, 1)
        self.redesignRadio = QtGui.QRadioButton(self.scrollAreaWidgetContents)
        self.redesignRadio.setObjectName("redesignRadio")
        self.gridLayout_4.addWidget(self.redesignRadio, 4, 2, 1, 1)
        self.oreTypeCombo = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.oreTypeCombo.setEditable(False)
        self.oreTypeCombo.setObjectName("oreTypeCombo")
        self.gridLayout_4.addWidget(self.oreTypeCombo, 3, 1, 1, 2)
        self.projectNameLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.projectNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.projectNameLabel.setObjectName("projectNameLabel")
        self.gridLayout_4.addWidget(self.projectNameLabel, 1, 0, 1, 1)
        self.projectNameLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.projectNameLineEdit.setObjectName("projectNameLineEdit")
        self.gridLayout_4.addWidget(self.projectNameLineEdit, 1, 1, 1, 2)
        self.locationCombo = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.locationCombo.setEditable(False)
        self.locationCombo.setObjectName("locationCombo")
        self.gridLayout_4.addWidget(self.locationCombo, 2, 1, 1, 2)
        self.locationLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.locationLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.locationLabel.setObjectName("locationLabel")
        self.gridLayout_4.addWidget(self.locationLabel, 2, 0, 1, 1)
        self.initialDesignRadio = QtGui.QRadioButton(self.scrollAreaWidgetContents)
        self.initialDesignRadio.setCheckable(True)
        self.initialDesignRadio.setChecked(True)
        self.initialDesignRadio.setObjectName("initialDesignRadio")
        self.gridLayout_4.addWidget(self.initialDesignRadio, 4, 0, 1, 2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 3, 4, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.minExtractionLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.minExtractionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minExtractionLabel.setObjectName("minExtractionLabel")
        self.gridLayout_3.addWidget(self.minExtractionLabel, 1, 0, 1, 1)
        self.minExtractionSpin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.minExtractionSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minExtractionSpin.setPrefix("")
        self.minExtractionSpin.setDecimals(1)
        self.minExtractionSpin.setMaximum(90.0)
        self.minExtractionSpin.setProperty("value", 50.0)
        self.minExtractionSpin.setObjectName("minExtractionSpin")
        self.gridLayout_3.addWidget(self.minExtractionSpin, 1, 1, 1, 1)
        self.roomWidthLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.roomWidthLabel.setObjectName("roomWidthLabel")
        self.gridLayout_3.addWidget(self.roomWidthLabel, 1, 2, 1, 1)
        self.roomWidthSpin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.roomWidthSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roomWidthSpin.setMaximum(3000.0)
        self.roomWidthSpin.setProperty("value", 6.0)
        self.roomWidthSpin.setObjectName("roomWidthSpin")
        self.gridLayout_3.addWidget(self.roomWidthSpin, 1, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 4, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 5)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.widget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.continuousMinerRadio = QtGui.QRadioButton(self.widget)
        self.continuousMinerRadio.setChecked(False)
        self.continuousMinerRadio.setObjectName("continuousMinerRadio")
        self.gridLayout_2.addWidget(self.continuousMinerRadio, 1, 0, 1, 1)
        self.drillBlastRadio = QtGui.QRadioButton(self.widget)
        self.drillBlastRadio.setChecked(True)
        self.drillBlastRadio.setObjectName("drillBlastRadio")
        self.gridLayout_2.addWidget(self.drillBlastRadio, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(326, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 2, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_3.setContentsMargins(-1, -1, 1, 1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.line_6 = QtGui.QFrame(self.widget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_3.addWidget(self.line_6)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 3)
        self.verticalLayout_4.addWidget(self.widget)
        spacerItem3 = QtGui.QSpacerItem(20, 50, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        Wizard.addPage(self.projectDetailsPage)
        self.pillarStrengthPage = QtGui.QWizardPage()
        self.pillarStrengthPage.setObjectName("pillarStrengthPage")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.pillarStrengthPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea_3 = QtGui.QScrollArea(self.pillarStrengthPage)
        self.scrollArea_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_3.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 552, 336))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_6.setSpacing(19)
        self.verticalLayout_6.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 3, 0, 1, 2)
        self.label_12 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 2, 0, 1, 2)
        self.pillarFormulaCombo = QtGui.QComboBox(self.scrollAreaWidgetContents_3)
        self.pillarFormulaCombo.setObjectName("pillarFormulaCombo")
        self.gridLayout_6.addWidget(self.pillarFormulaCombo, 1, 1, 1, 1)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setSpacing(1)
        self.verticalLayout_14.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_13 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_14.addWidget(self.label_13)
        self.line_7 = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_14.addWidget(self.line_7)
        self.gridLayout_6.addLayout(self.verticalLayout_14, 0, 0, 1, 3)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 1, 2, 3, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_6)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.constantKLabel = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.constantKLabel.setObjectName("constantKLabel")
        self.gridLayout_5.addWidget(self.constantKLabel, 1, 0, 1, 1)
        self.constantKSpin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.constantKSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.constantKSpin.setDecimals(3)
        self.constantKSpin.setMaximum(2000.0)
        self.constantKSpin.setProperty("value", 15.0)
        self.constantKSpin.setObjectName("constantKSpin")
        self.gridLayout_5.addWidget(self.constantKSpin, 1, 1, 1, 1)
        self.constantALabel = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.constantALabel.setObjectName("constantALabel")
        self.gridLayout_5.addWidget(self.constantALabel, 1, 2, 1, 1)
        self.constantASpin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.constantASpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.constantASpin.setDecimals(3)
        self.constantASpin.setMinimum(-1.0)
        self.constantASpin.setMaximum(1.0)
        self.constantASpin.setProperty("value", -0.6)
        self.constantASpin.setObjectName("constantASpin")
        self.gridLayout_5.addWidget(self.constantASpin, 1, 3, 1, 1)
        self.bLabel = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.bLabel.setObjectName("bLabel")
        self.gridLayout_5.addWidget(self.bLabel, 1, 4, 1, 1)
        self.constantBSpin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_3)
        self.constantBSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.constantBSpin.setDecimals(3)
        self.constantBSpin.setMinimum(-1.0)
        self.constantBSpin.setMaximum(1.0)
        self.constantBSpin.setProperty("value", 0.4)
        self.constantBSpin.setObjectName("constantBSpin")
        self.gridLayout_5.addWidget(self.constantBSpin, 1, 5, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 1, 6, 1, 1)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setSpacing(1)
        self.verticalLayout_13.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_13.addWidget(self.label_5)
        self.line_5 = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_13.addWidget(self.line_5)
        self.gridLayout_5.addLayout(self.verticalLayout_13, 0, 0, 1, 7)
        self.verticalLayout_6.addLayout(self.gridLayout_5)
        spacerItem6 = QtGui.QSpacerItem(20, 123, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.addWidget(self.scrollArea_3)
        Wizard.addPage(self.pillarStrengthPage)
        self.geoPage = QtGui.QWizardPage()
        self.geoPage.setObjectName("geoPage")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.geoPage)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea_2 = QtGui.QScrollArea(self.geoPage)
        self.scrollArea_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 552, 336))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_11.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(378, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.line_4 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_10.addWidget(self.line_4)
        self.gridLayout.addLayout(self.verticalLayout_10, 0, 0, 1, 7)
        self.frictionAngleLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.frictionAngleLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.frictionAngleLabel.setObjectName("frictionAngleLabel")
        self.gridLayout.addWidget(self.frictionAngleLabel, 2, 0, 1, 1)
        self.sampleDiameterLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.sampleDiameterLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sampleDiameterLabel.setObjectName("sampleDiameterLabel")
        self.gridLayout.addWidget(self.sampleDiameterLabel, 3, 0, 1, 1)
        self.uniaxialCompressiveStrengthLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.uniaxialCompressiveStrengthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uniaxialCompressiveStrengthLabel.setObjectName("uniaxialCompressiveStrengthLabel")
        self.gridLayout.addWidget(self.uniaxialCompressiveStrengthLabel, 4, 0, 1, 2)
        self.uniaxStrengthSpin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.uniaxStrengthSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uniaxStrengthSpin.setMaximum(1000.0)
        self.uniaxStrengthSpin.setProperty("value", 38.47)
        self.uniaxStrengthSpin.setObjectName("uniaxStrengthSpin")
        self.gridLayout.addWidget(self.uniaxStrengthSpin, 4, 2, 1, 2)
        self.rmrLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.rmrLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rmrLabel.setObjectName("rmrLabel")
        self.gridLayout.addWidget(self.rmrLabel, 4, 4, 1, 1)
        self.rmrSpin = QtGui.QSpinBox(self.scrollAreaWidgetContents_2)
        self.rmrSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rmrSpin.setMaximum(100)
        self.rmrSpin.setProperty("value", 44)
        self.rmrSpin.setObjectName("rmrSpin")
        self.gridLayout.addWidget(self.rmrSpin, 4, 5, 1, 1)
        self.cohesionSpin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.cohesionSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cohesionSpin.setProperty("value", 0.2)
        self.cohesionSpin.setObjectName("cohesionSpin")
        self.gridLayout.addWidget(self.cohesionSpin, 2, 5, 1, 1)
        self.sampleHeightSpin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.sampleHeightSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sampleHeightSpin.setProperty("value", 1.0)
        self.sampleHeightSpin.setObjectName("sampleHeightSpin")
        self.gridLayout.addWidget(self.sampleHeightSpin, 3, 5, 1, 1)
        self.sampleHeightLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.sampleHeightLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sampleHeightLabel.setObjectName("sampleHeightLabel")
        self.gridLayout.addWidget(self.sampleHeightLabel, 3, 4, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(73, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 6, 4, 1)
        self.cuboidSampleRadio = QtGui.QRadioButton(self.scrollAreaWidgetContents_2)
        self.cuboidSampleRadio.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cuboidSampleRadio.setObjectName("cuboidSampleRadio")
        self.gridLayout.addWidget(self.cuboidSampleRadio, 1, 4, 1, 2)
        self.cohesionLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.cohesionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cohesionLabel.setObjectName("cohesionLabel")
        self.gridLayout.addWidget(self.cohesionLabel, 2, 4, 1, 1)
        self.cylindricalSampleRadio = QtGui.QRadioButton(self.scrollAreaWidgetContents_2)
        self.cylindricalSampleRadio.setChecked(True)
        self.cylindricalSampleRadio.setObjectName("cylindricalSampleRadio")
        self.gridLayout.addWidget(self.cylindricalSampleRadio, 1, 0, 1, 4)
        self.sampleDiameterSpin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.sampleDiameterSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sampleDiameterSpin.setProperty("value", 1.0)
        self.sampleDiameterSpin.setObjectName("sampleDiameterSpin")
        self.gridLayout.addWidget(self.sampleDiameterSpin, 3, 1, 1, 1)
        self.frictionAngleSpin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.frictionAngleSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.frictionAngleSpin.setMaximum(90.0)
        self.frictionAngleSpin.setProperty("value", 19.0)
        self.frictionAngleSpin.setObjectName("frictionAngleSpin")
        self.gridLayout.addWidget(self.frictionAngleSpin, 2, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout)
        spacerItem8 = QtGui.QSpacerItem(20, 24, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem8)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(378, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.line_3 = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_9.addWidget(self.line_3)
        self.gridLayout_7.addLayout(self.verticalLayout_9, 0, 0, 1, 5)
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 1, 0, 1, 1)
        self.seamHeightSpin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seamHeightSpin.sizePolicy().hasHeightForWidth())
        self.seamHeightSpin.setSizePolicy(sizePolicy)
        self.seamHeightSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.seamHeightSpin.setProperty("value", 4.0)
        self.seamHeightSpin.setObjectName("seamHeightSpin")
        self.gridLayout_7.addWidget(self.seamHeightSpin, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 1, 2, 1, 1)
        self.seamDipSpin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seamDipSpin.sizePolicy().hasHeightForWidth())
        self.seamDipSpin.setSizePolicy(sizePolicy)
        self.seamDipSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.seamDipSpin.setMaximum(90.0)
        self.seamDipSpin.setProperty("value", 15.0)
        self.seamDipSpin.setObjectName("seamDipSpin")
        self.gridLayout_7.addWidget(self.seamDipSpin, 1, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 2, 0, 1, 1)
        self.oreDepthSpin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oreDepthSpin.sizePolicy().hasHeightForWidth())
        self.oreDepthSpin.setSizePolicy(sizePolicy)
        self.oreDepthSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.oreDepthSpin.setMaximum(1000.0)
        self.oreDepthSpin.setProperty("value", 150.0)
        self.oreDepthSpin.setObjectName("oreDepthSpin")
        self.gridLayout_7.addWidget(self.oreDepthSpin, 2, 1, 1, 1)
        self.overburdenDensityLabel_2 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.overburdenDensityLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.overburdenDensityLabel_2.setObjectName("overburdenDensityLabel_2")
        self.gridLayout_7.addWidget(self.overburdenDensityLabel_2, 2, 2, 1, 1)
        self.floorDensitySpin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.floorDensitySpin.sizePolicy().hasHeightForWidth())
        self.floorDensitySpin.setSizePolicy(sizePolicy)
        self.floorDensitySpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.floorDensitySpin.setMaximum(1000.0)
        self.floorDensitySpin.setProperty("value", 20.0)
        self.floorDensitySpin.setObjectName("floorDensitySpin")
        self.gridLayout_7.addWidget(self.floorDensitySpin, 2, 3, 1, 1)
        self.overburdenDensityLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.overburdenDensityLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.overburdenDensityLabel.setObjectName("overburdenDensityLabel")
        self.gridLayout_7.addWidget(self.overburdenDensityLabel, 3, 0, 1, 1)
        self.overburdenDensitySpin = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overburdenDensitySpin.sizePolicy().hasHeightForWidth())
        self.overburdenDensitySpin.setSizePolicy(sizePolicy)
        self.overburdenDensitySpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.overburdenDensitySpin.setMaximum(1000.0)
        self.overburdenDensitySpin.setProperty("value", 20.0)
        self.overburdenDensitySpin.setObjectName("overburdenDensitySpin")
        self.gridLayout_7.addWidget(self.overburdenDensitySpin, 3, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem9, 1, 4, 3, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_7)
        spacerItem10 = QtGui.QSpacerItem(20, 24, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem10)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.addWidget(self.scrollArea_2)
        Wizard.addPage(self.geoPage)
        self.oreTypeLabel.setBuddy(self.oreTypeCombo)
        self.projectNameLabel.setBuddy(self.projectNameLineEdit)
        self.locationLabel.setBuddy(self.locationCombo)
        self.minExtractionLabel.setBuddy(self.minExtractionSpin)
        self.roomWidthLabel.setBuddy(self.roomWidthSpin)
        self.label_6.setBuddy(self.pillarFormulaCombo)
        self.constantKLabel.setBuddy(self.constantKSpin)
        self.constantALabel.setBuddy(self.constantASpin)
        self.bLabel.setBuddy(self.constantBSpin)
        self.frictionAngleLabel.setBuddy(self.frictionAngleSpin)
        self.sampleDiameterLabel.setBuddy(self.sampleDiameterSpin)
        self.uniaxialCompressiveStrengthLabel.setBuddy(self.uniaxStrengthSpin)
        self.rmrLabel.setBuddy(self.rmrSpin)
        self.sampleHeightLabel.setBuddy(self.sampleHeightSpin)
        self.cohesionLabel.setBuddy(self.cohesionSpin)
        self.label_10.setBuddy(self.seamHeightSpin)
        self.label_9.setBuddy(self.seamDipSpin)
        self.label_3.setBuddy(self.oreDepthSpin)
        self.overburdenDensityLabel_2.setBuddy(self.overburdenDensitySpin)
        self.overburdenDensityLabel.setBuddy(self.overburdenDensitySpin)

        self.retranslateUi(Wizard)
        self.locationCombo.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Wizard)
        Wizard.setTabOrder(self.projectNameLineEdit, self.locationCombo)
        Wizard.setTabOrder(self.locationCombo, self.oreTypeCombo)
        Wizard.setTabOrder(self.oreTypeCombo, self.initialDesignRadio)
        Wizard.setTabOrder(self.initialDesignRadio, self.redesignRadio)
        Wizard.setTabOrder(self.redesignRadio, self.minExtractionSpin)
        Wizard.setTabOrder(self.minExtractionSpin, self.roomWidthSpin)
        Wizard.setTabOrder(self.roomWidthSpin, self.continuousMinerRadio)
        Wizard.setTabOrder(self.continuousMinerRadio, self.drillBlastRadio)
        Wizard.setTabOrder(self.drillBlastRadio, self.pillarFormulaCombo)
        Wizard.setTabOrder(self.pillarFormulaCombo, self.constantKSpin)
        Wizard.setTabOrder(self.constantKSpin, self.constantASpin)
        Wizard.setTabOrder(self.constantASpin, self.constantBSpin)
        Wizard.setTabOrder(self.constantBSpin, self.cylindricalSampleRadio)
        Wizard.setTabOrder(self.cylindricalSampleRadio, self.cuboidSampleRadio)
        Wizard.setTabOrder(self.cuboidSampleRadio, self.frictionAngleSpin)
        Wizard.setTabOrder(self.frictionAngleSpin, self.cohesionSpin)
        Wizard.setTabOrder(self.cohesionSpin, self.sampleDiameterSpin)
        Wizard.setTabOrder(self.sampleDiameterSpin, self.sampleHeightSpin)
        Wizard.setTabOrder(self.sampleHeightSpin, self.uniaxStrengthSpin)
        Wizard.setTabOrder(self.uniaxStrengthSpin, self.rmrSpin)
        Wizard.setTabOrder(self.rmrSpin, self.seamHeightSpin)
        Wizard.setTabOrder(self.seamHeightSpin, self.oreDepthSpin)
        Wizard.setTabOrder(self.oreDepthSpin, self.overburdenDensitySpin)
        Wizard.setTabOrder(self.overburdenDensitySpin, self.seamDipSpin)
        Wizard.setTabOrder(self.seamDipSpin, self.floorDensitySpin)
        Wizard.setTabOrder(self.floorDensitySpin, self.scrollArea_2)
        Wizard.setTabOrder(self.scrollArea_2, self.textEdit)
        Wizard.setTabOrder(self.textEdit, self.scrollArea_3)
        Wizard.setTabOrder(self.scrollArea_3, self.scrollArea)

    def retranslateUi(self, Wizard):
        Wizard.setWindowTitle(QtGui.QApplication.translate("Wizard", "Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit.setHtml(QtGui.QApplication.translate("Wizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:600;\">Read the following carefully</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:10pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt;\">This wizard will guide you through creating a new room and pillar (RAP) project. Defaults have been supplied for each of the various fields required. Please change these defaults to values that actually appy to your project.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:10pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt;\">On the project details page, if you select </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-style:italic;\">initial design</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt;\"> as the design type, the other data you entered will be used to evaluate the best method for design your RAP project. Choosing </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-style:italic;\">redesign</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt;\"> allows you more control over the methods used to design your RAP project. It is also expected that you will have more geotechnical data in such a situation and as such so may need to supply some parameters.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:10pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt;\">All thanks from </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-style:italic;\">Charis Optimal Systems </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt;\">and good luck.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.oreTypeLabel.setText(QtGui.QApplication.translate("Wizard", "&Ore Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.redesignRadio.setText(QtGui.QApplication.translate("Wizard", "&Redesign", None, QtGui.QApplication.UnicodeUTF8))
        self.projectNameLabel.setText(QtGui.QApplication.translate("Wizard", "&Project Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.projectNameLineEdit.setText(QtGui.QApplication.translate("Wizard", "New RAP Project", None, QtGui.QApplication.UnicodeUTF8))
        self.locationLabel.setText(QtGui.QApplication.translate("Wizard", "&Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.initialDesignRadio.setText(QtGui.QApplication.translate("Wizard", "&Initial Design", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Wizard", "General Information", None, QtGui.QApplication.UnicodeUTF8))
        self.minExtractionLabel.setText(QtGui.QApplication.translate("Wizard", "&Minimum Extraction:", None, QtGui.QApplication.UnicodeUTF8))
        self.minExtractionSpin.setSuffix(QtGui.QApplication.translate("Wizard", " %", None, QtGui.QApplication.UnicodeUTF8))
        self.roomWidthLabel.setText(QtGui.QApplication.translate("Wizard", "Initial Room &Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.roomWidthSpin.setSuffix(QtGui.QApplication.translate("Wizard", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Wizard", "Other Information", None, QtGui.QApplication.UnicodeUTF8))
        self.continuousMinerRadio.setText(QtGui.QApplication.translate("Wizard", "&Continuous Miner", None, QtGui.QApplication.UnicodeUTF8))
        self.drillBlastRadio.setText(QtGui.QApplication.translate("Wizard", "&Drill and Blast", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Wizard", "Fragmentation Method", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Wizard", "&Pillar Strength Formula:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Wizard", "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Type 2  S</span><span style=\" font-size:14pt; vertical-align:sub;\">P</span><span style=\" font-size:14pt;\"> = </span><span style=\" font-size:14pt; color:#ff0000;\">k</span><span style=\" font-size:14pt;\">(</span><span style=\" font-size:14pt; color:#ff0000;\">A</span><span style=\" font-size:14pt;\"> + </span><span style=\" font-size:14pt; color:#ff0000;\">B</span><span style=\" font-size:14pt;\">(H/W))</span></p>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Wizard", "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Type 1 S</span><span style=\" font-size:14pt; vertical-align:sub;\">P</span><span style=\" font-size:14pt;\"> = <span style=\" font-size:14pt; color:#ff0000;\">k</span>H</span><span style=\" font-size:14pt; color:#ff0000; vertical-align:super;\">A</span><span style=\" font-size:14pt;\">W</span><span style=\" font-size:14pt; color:#ff0000; vertical-align:super;\">B                  </span></p>\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Wizard", "Formula for Pillar Strength", None, QtGui.QApplication.UnicodeUTF8))
        self.constantKLabel.setText(QtGui.QApplication.translate("Wizard", "&k:", None, QtGui.QApplication.UnicodeUTF8))
        self.constantALabel.setText(QtGui.QApplication.translate("Wizard", "&A", None, QtGui.QApplication.UnicodeUTF8))
        self.bLabel.setText(QtGui.QApplication.translate("Wizard", "&B:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Wizard", "Formula Constants", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Wizard", "Geotechnical Information", None, QtGui.QApplication.UnicodeUTF8))
        self.frictionAngleLabel.setText(QtGui.QApplication.translate("Wizard", "&Friction Angle:", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleDiameterLabel.setText(QtGui.QApplication.translate("Wizard", "Sample &Diameter:", None, QtGui.QApplication.UnicodeUTF8))
        self.uniaxialCompressiveStrengthLabel.setText(QtGui.QApplication.translate("Wizard", "&Uniaxial Compressive Strength:", None, QtGui.QApplication.UnicodeUTF8))
        self.uniaxStrengthSpin.setSuffix(QtGui.QApplication.translate("Wizard", " MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.rmrLabel.setText(QtGui.QApplication.translate("Wizard", "&RMR:", None, QtGui.QApplication.UnicodeUTF8))
        self.cohesionSpin.setSuffix(QtGui.QApplication.translate("Wizard", " MPa", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleHeightSpin.setSuffix(QtGui.QApplication.translate("Wizard", " in", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleHeightLabel.setText(QtGui.QApplication.translate("Wizard", "Sample &Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.cuboidSampleRadio.setText(QtGui.QApplication.translate("Wizard", "Cu&bical/Cuboid Sample", None, QtGui.QApplication.UnicodeUTF8))
        self.cohesionLabel.setText(QtGui.QApplication.translate("Wizard", "&Cohesion:", None, QtGui.QApplication.UnicodeUTF8))
        self.cylindricalSampleRadio.setText(QtGui.QApplication.translate("Wizard", "C&ylindrical Sample", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleDiameterSpin.setSuffix(QtGui.QApplication.translate("Wizard", " in", None, QtGui.QApplication.UnicodeUTF8))
        self.frictionAngleSpin.setSuffix(QtGui.QApplication.translate("Wizard", " °", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Wizard", "Geological Information", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Wizard", "Seam Hei&ght:", None, QtGui.QApplication.UnicodeUTF8))
        self.seamHeightSpin.setSuffix(QtGui.QApplication.translate("Wizard", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Wizard", "Sea&m Dip:", None, QtGui.QApplication.UnicodeUTF8))
        self.seamDipSpin.setSuffix(QtGui.QApplication.translate("Wizard", " °", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Wizard", "&Depth of Mine:", None, QtGui.QApplication.UnicodeUTF8))
        self.oreDepthSpin.setSuffix(QtGui.QApplication.translate("Wizard", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.overburdenDensityLabel_2.setText(QtGui.QApplication.translate("Wizard", "<html><head/><body><p>&amp;Floor SG:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.floorDensitySpin.setSuffix(QtGui.QApplication.translate("Wizard", " kg/m³", None, QtGui.QApplication.UnicodeUTF8))
        self.overburdenDensityLabel.setText(QtGui.QApplication.translate("Wizard", "<html><head/><body><p>&amp;Overburden SG:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.overburdenDensitySpin.setSuffix(QtGui.QApplication.translate("Wizard", " kg/m3", None, QtGui.QApplication.UnicodeUTF8))

