# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/geotech.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GeotechPage(object):
    def setupUi(self, GeotechPage):
        GeotechPage.setObjectName(_fromUtf8("GeotechPage"))
        GeotechPage.resize(396, 283)
        self.verticalLayout_4 = QtGui.QVBoxLayout(GeotechPage)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_6 = QtGui.QLabel(GeotechPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.line = QtGui.QFrame(GeotechPage)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.frame_2 = QtGui.QFrame(GeotechPage)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_2.setHorizontalSpacing(12)
        self.gridLayout_2.setVerticalSpacing(7)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.sampleDensitySpin = QtGui.QDoubleSpinBox(self.frame_2)
        self.sampleDensitySpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sampleDensitySpin.setObjectName(_fromUtf8("sampleDensitySpin"))
        self.gridLayout_2.addWidget(self.sampleDensitySpin, 4, 1, 1, 1)
        self.sampleWidth = QtGui.QDoubleSpinBox(self.frame_2)
        self.sampleWidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sampleWidth.setObjectName(_fromUtf8("sampleWidth"))
        self.gridLayout_2.addWidget(self.sampleWidth, 3, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 3, 2, 1, 1)
        self.sampleDiameterSpin = QtGui.QDoubleSpinBox(self.frame_2)
        self.sampleDiameterSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sampleDiameterSpin.setObjectName(_fromUtf8("sampleDiameterSpin"))
        self.gridLayout_2.addWidget(self.sampleDiameterSpin, 2, 3, 1, 1)
        self.sampleHeightSpin = QtGui.QDoubleSpinBox(self.frame_2)
        self.sampleHeightSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sampleHeightSpin.setObjectName(_fromUtf8("sampleHeightSpin"))
        self.gridLayout_2.addWidget(self.sampleHeightSpin, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 2, 1, 1)
        self.sampleLengthSpin = QtGui.QDoubleSpinBox(self.frame_2)
        self.sampleLengthSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sampleLengthSpin.setObjectName(_fromUtf8("sampleLengthSpin"))
        self.gridLayout_2.addWidget(self.sampleLengthSpin, 3, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.label = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.unicompStrengthSpin = QtGui.QDoubleSpinBox(self.frame_2)
        self.unicompStrengthSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unicompStrengthSpin.setObjectName(_fromUtf8("unicompStrengthSpin"))
        self.gridLayout_2.addWidget(self.unicompStrengthSpin, 0, 2, 1, 2)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_7 = QtGui.QLabel(GeotechPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.line_2 = QtGui.QFrame(GeotechPage)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.frame = QtGui.QFrame(GeotechPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_11 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout.addWidget(self.label_11)
        self.spinBox = QtGui.QSpinBox(self.frame)
        self.spinBox.setFrame(True)
        self.spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox.setMaximum(100)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout.addWidget(self.spinBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.doubleSpinBox_6 = QtGui.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_6.setObjectName(_fromUtf8("doubleSpinBox_6"))
        self.gridLayout.addWidget(self.doubleSpinBox_6, 0, 1, 1, 1)
        self.doubleSpinBox_7 = QtGui.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_7.setMaximum(90.0)
        self.doubleSpinBox_7.setObjectName(_fromUtf8("doubleSpinBox_7"))
        self.gridLayout.addWidget(self.doubleSpinBox_7, 0, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.frame)
        self.label_10.setBuddy(self.sampleDensitySpin)
        self.label_2.setBuddy(self.sampleHeightSpin)
        self.label_4.setBuddy(self.sampleLengthSpin)
        self.label_5.setBuddy(self.sampleDiameterSpin)
        self.label_3.setBuddy(self.sampleWidth)
        self.label.setBuddy(self.unicompStrengthSpin)
        self.label_11.setBuddy(self.spinBox)
        self.label_8.setBuddy(self.doubleSpinBox_6)
        self.label_9.setBuddy(self.doubleSpinBox_7)

        self.retranslateUi(GeotechPage)
        QtCore.QMetaObject.connectSlotsByName(GeotechPage)
        GeotechPage.setTabOrder(self.unicompStrengthSpin, self.sampleHeightSpin)
        GeotechPage.setTabOrder(self.sampleHeightSpin, self.sampleDiameterSpin)
        GeotechPage.setTabOrder(self.sampleDiameterSpin, self.sampleWidth)
        GeotechPage.setTabOrder(self.sampleWidth, self.sampleLengthSpin)
        GeotechPage.setTabOrder(self.sampleLengthSpin, self.sampleDensitySpin)
        GeotechPage.setTabOrder(self.sampleDensitySpin, self.spinBox)
        GeotechPage.setTabOrder(self.spinBox, self.doubleSpinBox_6)
        GeotechPage.setTabOrder(self.doubleSpinBox_6, self.doubleSpinBox_7)

    def retranslateUi(self, GeotechPage):
        GeotechPage.setWindowTitle(_translate("GeotechPage", "WizardPage", None))
        GeotechPage.setTitle(_translate("GeotechPage", "Geotechnical Parameters", None))
        GeotechPage.setSubTitle(_translate("GeotechPage", "Fill in the necessary geotechnical parameters below.", None))
        self.label_6.setText(_translate("GeotechPage", "Sample Properties", None))
        self.sampleDensitySpin.setSuffix(_translate("GeotechPage", " m", None))
        self.sampleWidth.setSuffix(_translate("GeotechPage", " m", None))
        self.label_10.setText(_translate("GeotechPage", "D&ensity:", None))
        self.label_2.setText(_translate("GeotechPage", "&Height:", None))
        self.label_4.setText(_translate("GeotechPage", "&Length:", None))
        self.sampleDiameterSpin.setSuffix(_translate("GeotechPage", " m", None))
        self.sampleHeightSpin.setSuffix(_translate("GeotechPage", " m", None))
        self.label_5.setText(_translate("GeotechPage", "&Diameter:", None))
        self.sampleLengthSpin.setSuffix(_translate("GeotechPage", " m", None))
        self.label_3.setText(_translate("GeotechPage", "&Width:", None))
        self.label.setText(_translate("GeotechPage", "&Uniaxial Compressive Strength:", None))
        self.unicompStrengthSpin.setSuffix(_translate("GeotechPage", " MPa", None))
        self.label_7.setText(_translate("GeotechPage", "Other Parameters", None))
        self.label_11.setText(_translate("GeotechPage", "&Rock Mass Rating:", None))
        self.doubleSpinBox_6.setSuffix(_translate("GeotechPage", " MPa", None))
        self.doubleSpinBox_7.setSuffix(_translate("GeotechPage", " °", None))
        self.label_8.setText(_translate("GeotechPage", "&Cohesion:", None))
        self.label_9.setText(_translate("GeotechPage", "&Friction Angle", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    GeotechPage = QtGui.QWizardPage()
    ui = Ui_GeotechPage()
    ui.setupUi(GeotechPage)
    GeotechPage.show()
    sys.exit(app.exec_())

